# =========================
# SERVER CONFIGURATION
# =========================

# TODO:
# Set server port (example: 9191)

server.port=?????

# =========================
# H2 DATABASE CONFIG
# =========================

# TODO:
# Add H2 in-memory database URL

spring.datasource.url=?????

# TODO:
# Driver class name (H2 driver)

spring.datasource.driverClassName=?????

# TODO:
# Username (default is sa)

spring.datasource.username=?????

# TODO:
# Password (leave empty)

spring.datasource.password=?????

# =========================
# JPA CONFIGURATION
# =========================

# TODO:
# Enable auto table creation/update

spring.jpa.hibernate.ddl-auto=?????

# TODO:
# Show SQL queries in console

spring.jpa.show-sql=?????

# =========================
# H2 CONSOLE (OPTIONAL BUT USEFUL)
# =========================

# TODO:
# Enable browser console for DB

spring.h2.console.enabled=?????